---
kind: pipeline
type: docker
name: verify-pr
steps:
- name: test
  image: danlynn/ember-cli:3.28.5
  commands:
  - npm install
  - npm test
trigger:
  event:
    - push

---
kind: pipeline
type: docker
name: release
steps:
- name: npm-release
  image: plugins/npm
  settings:
    token:
      from_secret: npm_access_token
trigger:
  event:
    - tag
---
kind: secret
name: npm_access_token
data: P69W9Ln4k9/82yP1oLB/vuqid3XV4ZsbmRS1AfGvQ+q9eZ52PQdBYg4jg1/BmWCwXwjX8nIQPEs1caKHg40Q3rC4jJU=
